name              "up_limits"
description       ""
long_description  IO.read(File.join(File.dirname(__FILE__), "README.md"))
maintainer        "Martin Peck"
maintainer_email  "coderman@protonmail.com"
version           "1.0.0"
supports          "ubuntu"
supports          "amazon"
supports          "centos"
supports          "fedora"
supports          "freebsd"
supports          "debian"
supports          "oracle"
supports          "mac_os_x"
supports          "redhat"
supports          "suse"
supports          "opensuse"
supports          "opensuseleap"
supports          "zlinux"
